# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, colour, diagramsCore, diagramsLib, ghcjsBase, ghcjsCanvas
, lens, mtl, NumInstances, text, vectorSpace, diagramsGhcjs
}:

cabal.mkDerivation (self: {
  pname = "diagrams-ghcjs-tests";
  version = "0.2.0";
  src = ./.;
  buildDepends = [
    colour diagramsCore diagramsLib ghcjsBase ghcjsCanvas lens mtl
    NumInstances text vectorSpace diagramsGhcjs
  ];
})
