# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, colour, diagramsCore, diagramsLib, ghcjsBase, ghcjsCanvas
, lens, mtl, NumInstances, text, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "diagrams-ghcjs";
  version = "0.2.0";
  src = ./.;
  buildDepends = [
    colour diagramsCore diagramsLib ghcjsBase ghcjsCanvas lens mtl
    NumInstances text vectorSpace
  ];
  meta = {
    homepage = "http://projects.haskell.org/diagrams/";
    description = "GHCJS backend for diagrams drawing EDSL";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
